version: "3.7"
services:

    db:
        build : ./db
        container_name: db
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_DATABASE: "clothers"
        restart: always
        volumes:
            - ./db/data:/var/lib/mysql:rw
        command:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
            - "3327:3306"
    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_USER: root
        depends_on:
            - db
    php:
        container_name: php
        build: ./php
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www/symfony_docker
        depends_on:
            - db
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '3900:80'
        volumes:
            - ./app:/var/www/symfony_docker
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
networks:
    dev:
