INSERT INTO `regions` VALUES (1, 'Auvergne-Rhône-Alpes');
INSERT INTO `regions` VALUES (2, 'Bourgogne-Franche-Comté');
INSERT INTO `regions` VALUES (3, 'Bretagne');
INSERT INTO `regions` VALUES (4, 'Centre-Val de Loire');
INSERT INTO `regions` VALUES (5, 'Corse');
INSERT INTO `regions` VALUES (6, 'Grand Est');
INSERT INTO `regions` VALUES (7, 'Hauts-de-France');
INSERT INTO `regions` VALUES (8, 'Île-de-France');
INSERT INTO `regions` VALUES (9, 'Normandie');
INSERT INTO `regions` VALUES (10, 'Nouvelle-Aquitaine');
INSERT INTO `regions` VALUES (11, 'Occitanie');
INSERT INTO `regions` VALUES (12, 'Pays de la Loire');
INSERT INTO `regions` VALUES (13, 'Provence-Alpes-Côte d\'Azur');