INSERT INTO `roles` VALUES (1, 'Auvergne-Rhône-Alpes');
INSERT INTO `roles` VALUES (2, 'Bourgogne-Franche-Comté');
INSERT INTO `roles` VALUES (3, 'Bretagne');
INSERT INTO `roles` VALUES (4, 'Centre-Val de Loire');
INSERT INTO `roles` VALUES (5, 'Corse');
INSERT INTO `roles` VALUES (6, 'Grand Est');
INSERT INTO `roles` VALUES (7, 'Hauts-de-France');
INSERT INTO `roles` VALUES (8, 'Île-de-France');
INSERT INTO `roles` VALUES (9, 'Normandie');
INSERT INTO `roles` VALUES (10, 'Nouvelle-Aquitaine');
INSERT INTO `roles` VALUES (11, 'Occitanie');
INSERT INTO `roles` VALUES (12, 'Pays de la Loire');
INSERT INTO `roles` VALUES (13, 'Provence-Alpes-Côte d\'Azur');
INSERT INTO `roles` VALUES (14, 'France');
INSERT INTO `roles` VALUES (15, 'Sud-Est');