insert into stores (id, name, address, region_id) values (1, 'Lorrie', '152 Texas Junction', 1);
insert into stores (id, name, address, region_id) values (2, 'Melba', '59 Hollow Ridge Plaza', 2);
insert into stores (id, name, address, region_id) values (3, 'Quintin', '2 Kinsman Plaza', 3);
insert into stores (id, name, address, region_id) values (4, 'Franklin', '45 Sauthoff Center', 4);
insert into stores (id, name, address, region_id) values (5, 'Marji', '53075 Kingsford Pass', 5);
insert into stores (id, name, address, region_id) values (6, 'Marylin', '1891 Burrows Crossing', 6);
insert into stores (id, name, address, region_id) values (7, 'Shellie', '57 Brown Circle', 7);
insert into stores (id, name, address, region_id) values (8, 'Joe', '07 Sutherland Point', 8);
insert into stores (id, name, address, region_id) values (9, 'Lina', '225 Marquette Park', 9);
insert into stores (id, name, address, region_id) values (10, 'Manfred', '255 Mesta Lane', 10);
insert into stores (id, name, address, region_id) values (11, 'Moishe', '338 Corben Road', 11);
insert into stores (id, name, address, region_id) values (12, 'Sky', '651 Huxley Way', 12);
insert into stores (id, name, address, region_id) values (13, 'Philip', '6325 Dovetail Avenue', 13);
insert into stores (id, name, address, region_id) values (14, 'Burl', '27935 Morrow Plaza', 1);
insert into stores (id, name, address, region_id) values (15, 'Harry', '81 Gale Point', 2);
insert into stores (id, name, address, region_id) values (16, 'Zelma', '7732 Lakeland Plaza', 3);
insert into stores (id, name, address, region_id) values (17, 'Aubert', '016 Redwing Street', 4);
insert into stores (id, name, address, region_id) values (18, 'Mata', '34 Rowland Circle', 5);
insert into stores (id, name, address, region_id) values (19, 'Coretta', '2 Florence Lane', 6);
insert into stores (id, name, address, region_id) values (20, 'Jourdan', '34 Hoard Court', 7);
insert into stores (id, name, address, region_id) values (21, 'Latashia', '0851 Burning Wood Way', 8);
insert into stores (id, name, address, region_id) values (22, 'Rancell', '2846 Nancy Hill', 9);
insert into stores (id, name, address, region_id) values (23, 'Tom', '60 Commercial Point', 10);
insert into stores (id, name, address, region_id) values (24, 'Kitti', '55960 Anhalt Lane', 11);
insert into stores (id, name, address, region_id) values (25, 'Clint', '404 Rutledge Center', 12);
insert into stores (id, name, address, region_id) values (26, 'Jacquelynn', '89 Badeau Avenue', 13);
insert into stores (id, name, address, region_id) values (27, 'Olympe', '29421 Pine View Place', 1);
insert into stores (id, name, address, region_id) values (28, 'Sherman', '93 Forest Plaza', 2);
insert into stores (id, name, address, region_id) values (29, 'Bil', '16 Pankratz Lane', 3);
insert into stores (id, name, address, region_id) values (30, 'Field', '309 Pine View Avenue', 4);
